{% set name = "pybrush" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/cavalab/brush/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fe64b9ef82e21d3a2a6c9871efec9f7a103234faa51d2e6fe32df68761fa605c

build:
  skip: True  # [not linux]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python #>=3.8
    - cmake #=3.18.*
    - eigen #=3.4.*
    - fmt
    - gcc >= 12.0
    - gxx >= 12.0
    - ninja
    - ceres-solver
    - pybind11 #=2.6.2
    - pytest #=6.2.4
    - pydot
    - scikit-learn
    - pandas
    - pip:
      - graphviz
      - deap
      - pmlb
  run:
    - python #>=3.8

test:
  imports:
    - numpy
    - pandas
    - pmlb
    - json
    - pickle

about:
  home: https://github.com/cavalab/brush
  summary: 
  description: |
    Brush is a strongly-typed genetic programming language. It is designed for
    **b**ackpropagations and **r**ecursion **u**sing **s**earch **h**euristics.
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: http://cavalab.org/brush/
  dev_url: https://github.com/cavalab/brush